matrix:
  allow_failures:
        - rvm: ruby-head
        - rvm: jruby-19mode
        - rvm: rbx-19mode
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
  - ruby-head
branches:
  only: master
notifications:
  email: false
